name: CI-dev-pipeline
on:
  push:
    branches:
      - main
  pull_request:

env:
  SERVICE: omo-devops-test-task
  SITE: vs-studio
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    #container:
      #image: lucasalt/act_base:latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: "${{env.SERVICE}}"
      - uses: actions/checkout@v2
        with:
          path: "${{env.SITE}}"

      - name: ls files
        run: | 
          ls -a
          ls "${{env.SITE}}"
          ls ${{env.SERVICE}}

      - name: Build docker tool
        working-directory: ${{env.SERVICE}}
        run: env

      - name: Build docker tool
        working-directory: ${{env.SERVICE}}
        run: docker build --file Dockerfile .

#       - name: Run test
#         run: |
#           echo --- Running test cases ---
#           docker-compose -f ./<REPO_NAME>/docker-compose.test-github.yml -p testing up --build --exit-code-from api-test
#           echo --- Completed test cases ---
        
