name: CI-dev-pipeline
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lucasalt/act_base:latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: "omo-devops-test-task"

      - name: ls files
        run: | 
          ls -a

#       - name: Build docker
#         run: | 
#           echo ---Building and starting up docker---
#           docker-compose -f ./<REPO_NAME>/docker-compose.test.yml -p testing up -d
#           echo ---Containers up---

#       - name: Run test
#         run: |
#           echo --- Running test cases ---
#           docker-compose -f ./<REPO_NAME>/docker-compose.test-github.yml -p testing up --build --exit-code-from api-test
#           echo --- Completed test cases ---
        
