name: CI-dev-pipeline
on:
  push:
    branches:
      - main
  pull_request:

env:
  SERVICE: omo-devops-test-task
  SITE: site-sample
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    #container:
      #image: lucasalt/act_base:latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: "$SERVICE"
      - uses: actions/checkout@v2
        with:
          path: "vs-studio"

      - name: ls files
        run: | 
          ls -a
          ls vs-studio
          ls omo-devops-test-task

      - name: Build docker tool
        working-directory: $SERVICE
        run: docker build --file $SERVICE/Dockerfile .

#       - name: Run test
#         run: |
#           echo --- Running test cases ---
#           docker-compose -f ./<REPO_NAME>/docker-compose.test-github.yml -p testing up --build --exit-code-from api-test
#           echo --- Completed test cases ---
        
