name: Yarn
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install 
      - name: yarn test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
      - name: yarn build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - name: Test Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        
